### ISSUE TITLE
version not found: left-pad@0.0.3 in Exercise 8

### ISSUE THREAD

**Issue by shaosh** [workshopper/learnyoureact#100]
In Exercise 8, when I was trying to install the npm packages babelify, babel-preset-react and babel-preset-es2015, it returns "version not found: left-pad@0.0.3". Is it possible to replace these packages use other packages?

**Comment by kohei-takata** [comment]
I think it have been fixed.
Please run `npm install browserify babelify babel-preset-react babel-preset-es2015` command again :)
