### ISSUE TITLE
Add new exercises

### ISSUE THREAD

**Issue by kohei-takata** [workshopper/learnyoureact#14]
Add excercises
- [x] isomorphic
- [x] css2
- [x] event(Add Todo)
- [x] prop_and_state(Delete Todo)

Translation(English)
- [x] isomorphic
- [x] css2
- [x] event(Add Todo)
- [x] prop_and_state(Delete Todo)

**Comment by gitseitanaka** [comment]
日本語で恐縮です。
latest commit 4b1679e209 時点の環境を用いて
isomorphicを実行したのですが、以下エラーとなります。
browserifyは、browserify@10.2.0及び10.1.3で試してみました。

初歩的な手順ミスの可能性がございますが、
お気づきの点、ありましたらご教示いただきたく。

```
C:\Users\user\nodeschool\learnyoureact\isomorphic>learnyoureact verify solution.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\user\nodeschool\learnyoureact\isomorphic\solution.js:7:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
✗ Error connecting to http://localhost:62164: ECONNREFUSED
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
```

環境は、Windows7 node 0.12.2です。
learnyoureact/exercises/isomorphic/solution のコードで試しました。

**Comment by marocchino** [comment]
@gitseitanaka `npm install browserify`をした後に試してみてください。

**Comment by gitseitanaka** [comment]
@marocchino ありがとうございました。
"npm install browserify"で、うまく行きました。
"-g" オプションを付けていたのが敗因でした。
失礼いたしました。

**Comment by marocchino** [comment]
@gitseitanaka 良かったです！

**Comment by kohei-takata** [comment]
@marocchino 回答していただき、ありがとうございました！

@gitseitanaka reactify も同様にインストールする必要がありませんでしたか？
不親切なので、 hello_react みたいにプログラムの方にインストールしてくださいと記述するよう変更しておきます。

**Comment by marocchino** [comment]
:+1:

**Comment by gitseitanaka** [comment]
@tako-black 初歩的なところで申し訳ございませんでした。

reactify は先のエラー対応中に
"package.json"の以下追加をお見かけして、やみくもにinstallコマンドを叩いたことが功を奏したかは不明ですが、該当のエラーは発生しませんでした。

```
    "browserify": "~10.1.3",
    "reactify": "~1.1.1"

```

**Comment by kohei-takata** [comment]
@gitseitanaka いえいえ、動いて良かったです！

> 該当のエラーは発生しませんでした。

そうでしたか、多分 reactify も必要だと思うので、記述しておきますね。

**Comment by kohei-takata** [comment]
@gitseitanaka 度々すみません。 reactify はコンソールではエラーは出ませんが、ブラウザで見るとエラーが出るようで、表示はできますがチェックイベントが正しく動作しないようです。
やはり同様にインストールする必要があると思います。

**Comment by gitseitanaka** [comment]
@tako-black 返信遅れて申し訳ございません。

> 同様にインストールする必要があると思います。

おっしゃる通りでした。
昨日は、以下verifyオプションがパスすることだけを確認しており
ブラウザからの動作確認は行ってませんでした。

```
learnyoureact verify  solution.js
```

reactify を browserifyと同様にインストールしたところ
ブラウザ側でも表示が見えました。
ご指摘ありがとうございました。
＃ 色々動かして勉強させていただきます！！

**Comment by kohei-takata** [comment]
@gitseitanaka 

> reactify を browserifyと同様にインストールしたところ
> ブラウザ側でも表示が見えました。

良かったです！
