### ISSUE TITLE
Change Japanese explanatory texts simplify

### ISSUE THREAD

**Issue by kohei-takata** [workshopper/learnyoureact#26]
Now, explanatory texts are too difficult to understand.

**Comment by geirman** [comment]
I didn't find it useful because it's not all in enlgish

**Comment by kohei-takata** [comment]
@geirman 
Thank you for your comment.
Have you try `CHOOSE LANGUAGE`?
You can change languages by this command.

**Comment by geirman** [comment]
I didn't notice it. I'll check it out again when I have a sec. Thanks for the tip :)
