### ISSUE TITLE
Solution servers survive when submitted server doesn't start/respond

### ISSUE THREAD

**Issue by shuhei** [workshopper/learnyoureact#27]
Related to #22 

After enjoying this great workshop, I noticed that solution servers are still alive.

```
$ ps ax | grep node
  154   ??  S      0:00.76 /Users/shuhei/.nvm/versions/node/v0.12.0/bin/node /Users/shuhei/.nvm/versions/node/v0.12.0/lib/node_modules/learnyoureact/exercises/props_from_server/solution/solution.js 51137 Bread 14:00
  165   ??  S      0:00.74 /Users/shuhei/.nvm/versions/node/v0.12.0/bin/node /Users/shuhei/.nvm/versions/node/v0.12.0/lib/node_modules/learnyoureact/exercises/props_from_server/solution/solution.js 45928 Milk 13:00
  174   ??  S      0:00.70 /Users/shuhei/.nvm/versions/node/v0.12.0/bin/node /Users/shuhei/.nvm/versions/node/v0.12.0/lib/node_modules/learnyoureact/exercises/props_from_server/solution/solution.js 46569 Car 15:00
...
```

It seems like solution server survives when the command doesn't connect to submitted server. You can reproduce the phenomenon with the following steps:
1. Create an empty `program.js`
2. `learnyoureact` and choose an exercise.
3. `learnyoureact verify program.js`
4. `ps ax | grep node`

I'm still not sure if this is an issue of this repo or workshopper modules though.

**Comment by marocchino** [comment]
I think it's general in workshopper.
Express works has a [explanation](https://github.com/azat-co/expressworks/blob/master/exercises/hello_world/problem.md) of this problem

> Run `$ killall node`  before verifying exercises (in your terminal on Mac OS X) to end any previous processes. For Windows, use `taskkill /IM node.exe`.

**Comment by shuhei** [comment]
Thanks! Closing.
