### ISSUE TITLE
Change md files of Japanese and Korean

### ISSUE THREAD

**Issue by kohei-takata** [workshopper/learnyoureact#31]
We have to change md files like #30 .
- [x] hello_react/problem.md
- [ ] hello_react/problem.ko.md
- [x] components/problem.md
- [ ] components/problem.ko.md
- [x] proptypes/problem.md
- [ ] proptypes/problem.ko.md
- [x] css/problem.md
- [ ] css/problem.ko.md
- [x] state/problem.md
- [ ] state/problem.ko.md

**Comment by kohei-takata** [comment]
ping @marocchino

**Comment by marocchino** [comment]
got it. :ok_woman:

**Comment by kohei-takata** [comment]
Before do this, I think I must translate [ `jsx-in-depth.html` ](https://github.com/facebook/react/blob/gh-pages/docs/jsx-in-depth.html) to Japanese.

**Comment by kohei-takata** [comment]
And [ `reusable-components.html` ](https://github.com/facebook/react/blob/gh-pages/docs/reusable-components.html)
