### ISSUE TITLE
What challenges can/should be added to the workshop?

### ISSUE THREAD

**Issue by gyaresu** [workshopper/learnyoureact#37]
Hey @tako-black 

I really enjoyed going through the challenges so thank you!

I would like to go through again now and add more links to documentation and even add some more challenges about aspects of React that I am finding as a 'beginner' that would be beneficial to learn.

Do you have any thoughts on this? Are there any ideas you have had but maybe no time to implement.

Thought I'd ask first before just diving in and changing your workshop :)

Thanks.

**Comment by kohei-takata** [comment]
Hi @gyaresu 
Thank you for your opening issue!

Of course PR is welcome! If you have some ideas to implement, please make PR!

**Comment by gyaresu** [comment]
:+1: Thanks!
