### ISSUE TITLE
Use ES6 and Babel

### ISSUE THREAD

**Issue by kohei-takata** [workshopper/learnyoureact#43]

**Comment by aksharpatel47** [comment]
I would like to help out with this issue. Can someone can point me in the right direction?

**Comment by kohei-takata** [comment]
Hi @aksharpatel47 !
Thank you for your comment!

I think files in `learnyoureact/exercises/*/solution/`, and `problem.*.md` files can be changed.
Files will be `.jsx` or `.js` or `.md`.
Once you change `.jsx` files, please add [`transformViews` option](https://github.com/reactjs/express-react-views#options)  in `solution.js` file.
After that it will move correctly.

After change `.js` files, please use `Babel` to transpile the file.

Finally, you must change `.md` files of question.

Please ask me anything if you have any questions while changing.
Thanks.

Kohei

**Comment by aksharpatel47** [comment]
Hi @tako-black 

Thanks for replying. I'll get to work on it and will let you know in case I need your help.

**Comment by atuttle** [comment]
Another related issue is that the examples currently use [node-jsx](https://github.com/petehunt/node-jsx) which has been [deprecated in favor of Babel](https://github.com/petehunt/node-jsx/issues/44). I'm not good enough with Babel yet to know how to rewrite the sample app using it, but I figured I'd mention that.

**Comment by kohei-takata** [comment]
Hi @atuttle 
Thanks for your mention!
I think `require('node-jsx').install()` should be `require('babel/register')`.

**Comment by atuttle** [comment]
I tried your suggestion (even did `npm uninstall node-jsx`) and it worked. Seems good to me! I'll get a PR in to make that change, soon.
