### ISSUE TITLE
Isomorphic explanation is a little lacking

### ISSUE THREAD

**Issue by cyber2024** [workshopper/learnyoureact#46]
Hi Guys, great tutorials!

I am working my way through all of them.

Can you please review and revise the descriptions in ISOMORPHIC.
I am having trouble learning from it because some of the English is a little off.

Also, there are some huge changes to the app, yet they are hardly explained.

Thanks again!

-Russ

**Comment by kohei-takata** [comment]
Hi @cyber2024 !
Thank you for your issue!
I' sorry that the descriptions are bad to learn.

I want to change the descriptions, but I cannot find the bad point, because I'm not good at English.
So if you tell me the bad point or make PR for that, I'm very happy.

Thanks.

Kohei

**Comment by cyber2024** [comment]
Sure, no problem, I'll take another look at it for you when I have time!

**Comment by atuttle** [comment]
This is improved (but still not awesome) in #67
