### ISSUE TITLE
Exercise 5 not properly checking solution or working 

### ISSUE THREAD

**Issue by wardy** [workshopper/learnyoureact#47]
The handleChange function is never called, even when the whole task verifies.

This is probably due to the way that the tutorials server is set up. After putting the code into a single page like the react tutorial suggests the event actually fires.

**Comment by kohei-takata** [comment]
Hi @wardywork !
Thank you for your issue!

I know that problem, but I didn't fix, because that is the task of the later exercise!
Please do exercise until the last, you will find the meaning.

Thanks.

Kohei
