### ISSUE TITLE
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated.

### ISSUE THREAD

**Issue by naru0504** [workshopper/learnyoureact#48]
![image](https://cloud.githubusercontent.com/assets/8326452/9329690/d4fa2108-45ee-11e5-9079-c4c6ccbcff13.png)

https://fb.me/react-tools-deprecated

**Comment by naru0504** [comment]
It seems a problem of "express-react-views": "~0.7.2"

**Comment by kohei-takata** [comment]
Thanks! Fixed!
Please use v0.9.10.

**Comment by naru0504** [comment]
No problem, and thanks to you too.
