### ISSUE TITLE
Solution not working for state and mutable values exercise

### ISSUE THREAD

**Issue by alayek** [workshopper/learnyoureact#56]
I wrote the `handleChange()` function and used the `setState()` function inside it. But when I am running `verify`, it is not passing the test case.

In particular, I am getting this:

```
1.  ACTUAL:    "<!DOCTYPE html><div class=\"todoBox\"><h1>Todos</h1><div class=\"todoList\"><table style=\"border:2px solid black;\"><tbody><tr><td style=\"border:1px solid black;\"><input type=\"checkbox\"/></td><td style=\"border:1px solid black;\">Shopping</td><td style=\"border:1px solid black;\">Milk</td></tr><tr><td style=\"border:1px solid black;\"><input type=\"checkbox\"/></td><td style=\"border:1px solid black;\">Hair cut</td><td style=\"border:1px solid black;\">13:00</td></tr></tbody></table></div><div class=\"todoForm\">I am a TodoForm.</div></div>"
1.  EXPECTED:  "<!DOCTYPE html><div class=\"todoBox\"><h1>Todos</h1><div class=\"todoList\"><table style=\"border:2px solid black;\"><tbody><tr><td style=\"border:1px solid black;\"><input type=\"checkbox\"></td><td style=\"border:1px solid black;\">Shopping</td><td style=\"border:1px solid black;\">Milk</td></tr><tr><td style=\"border:1px solid black;\"><input type=\"checkbox\"></td><td style=\"border:1px solid black;\">Hair cut</td><td style=\"border:1px solid black;\">13:00</td></tr></tbody></table></div><div class=\"todoForm\">I am a TodoForm.</div></div>"
```

The `>` and `/>` after `checkbox` are different. I don't know what's going on.

I copy pasted the solution, but same issue. What am I doing wrong here?  I have also posted on the gitter channel, but no one responded.

Sorry if this is a coding issue on my part, but I need to get a response fast!

**Comment by kohei-takata** [comment]
Would you show me `index.jsx` file?
I've tried in my PC and run correctly.
I also write in [gitter](https://gitter.im/tako-black/learnyoureact).

**Comment by alayek** [comment]
Yes, of course.
http://pastebin.com/U9UxKwe4

**Comment by mreid1130** [comment]
Running into the same issue: http://pastebin.com/CXuKZGYv

**Comment by kohei-takata** [comment]
@alayek @mreid1130 
I'm afraid that I can't simulate your error at my PC.
I cannot find the bad point.
I'll update version of React to v0.14.0 in a few days.
I cannot promise you the error will fix, but please update version of `learnyoureact` and check again.

**Comment by alayek** [comment]
Thanks @tako-black. If you need remote access to my PC, my offer stands. I was also suspecting it must be a version thing.

**Comment by kohei-takata** [comment]
Hi @alayek @mreid1130 .
I updated the version of React.
Please use learnyoureact v0.9.14.
If the problem does not fix, please tell me again.

**Comment by rebmullin** [comment]
@alayek @tako-black - I was having a similar issue with learnyoureact v0.9.12. I've upgraded tho to v0.9.14 and now see the following results http://grab.by/Ldwa - see errors on lines 9 and 16?  Seems like the only way I could get it to pass was by removing `checked={checked} onChange={this.handleChange}` from the input element. is this an error or was this part not expected here?

**Comment by atuttle** [comment]
I'm having similar problems:

learnyoureact @ 0.9.16
react @ 0.14.0
node @ 4.1.1

When I run my program (not the run or verify command, just `node program.js`), and run it in the browser... it _appears_ functional. If I change my initial value for checked and restart the program, it appears to be respected. But if I add a `console.log()` or `alert()` statement to my `handleChange` method, it doesn't seem to run.

Additionally, the `verify` fails on these lines:

```
16. ACTUAL:    "                        <input type=\"checkbox\" checked=\"\" />"
16. EXPECTED:  "                        <input type=\"checkbox\" />"
```

**Comment by atuttle** [comment]
I've also noticed that there's _no_ JS in the page when I view the app. No JS file included, and no inline JS. That's probably why my console.log/alert calls aren't working, but why is it missing?

Update: after more research, it looks like the `express-react-views` module being used here only does the server-side rendering, so that would (probably?) explain why I'm not seeing any JS in the browser. I'm going to assume this is just a minor difference in HTML and move on to later lessons... but this issue with the HTML probably still needs to be resolved.

**Comment by atuttle** [comment]
Actually... it seems to be working fine for me now.

I had played a bit with the initial state (setting checked to true) to try and debug my console.log issue, and setting it back to the lesson-specified value of false makes the verification pass.
