### ISSUE TITLE
npm learnyoureact issue

### ISSUE THREAD

**Issue by js08** [workshopper/learnyoureact#58]
Hi,

I have node version 0.12.7 and npm version 2.11.3 installed in my machine, but after that if I install learnyoureact using the command npm install -g learnyoureact . I see an error which says learnyoureact  not found in npm registry.

Can you tell me how to fix it.

Thanks

**Comment by kohei-takata** [comment]
Is there any error logs when you run `npm install -g learnyoureact`?
Please show all the error log which says learnyoureact not found in npm registry if you can.

**Comment by js08** [comment]
Hey,

Thanks for your reply, I think below screenshot should help you out

![screen shot 2015-10-17 at 5 16 49 pm](https://cloud.githubusercontent.com/assets/1699943/10561554/e7fd15ac-74f2-11e5-856d-80a97b556077.png)

**Comment by js08** [comment]
Attaching you the latest version too
![screen shot 2015-10-17 at 5 18 36 pm](https://cloud.githubusercontent.com/assets/1699943/10561568/f84f52b6-74f3-11e5-943e-e863bc79d682.png)

**Comment by kohei-takata** [comment]
Please try `sudo npm install -g learnyoureact`.
You will have to input the password of your PC after run this command.

**Comment by js08** [comment]
yeah it works fine now

**Comment by js08** [comment]
hey sudo command is not working in windows environment, but it worked in mac. 
can you tell me how to fix in windows.

**Comment by kohei-takata** [comment]
I think you need to run `cmd.exe` as adminitrator.(Right click, run as admin)
I couldn't try because I don't have windows.

**Comment by js08** [comment]
@tako-black I ran as administrator but still I was not successful

**Comment by kohei-takata** [comment]
@rk08 What the error seems to say? EACCESS?
