### ISSUE TITLE
Can't combine front-end and server-side rendering

### ISSUE THREAD

**Issue by kohei-takata** [workshopper/learnyoureact#6]
I don't know how to use React.js event at front-end.
I want to add exercises of "Add `text-decoration: line-through` style to Todo if the Todo is checked" or "Delete Todos" or "Add Todos" by using front-end events.
Should I use browserify or reactify or etc?
If you know, please tell me how.
PR is welcome.

---

現在、このワークショッパーではサーバサイドレンダリングを行っていますが、これをフロントのイベントと組み合わせたいと思っています。
しかし、考えうる方法で試してみたのですが、うまくいきません。。。
具体的には、フロントのイベントを使用して、「Todoがチェックされた際にスタイルとして `text-decoration: line-through` を付ける」や「Todoを削除する」や「Todoを追加する」といったエクササイズを追加したいと思っています。
browserify や reactify を使う必要があるのでしょうか？
ご存知の方がいらっしゃったら、教えていただきたいです。
PRも歓迎です。

**Comment by fand** [comment]
[express-react-views](https://github.com/reactjs/express-react-views)は静的なHTMLを出力するので、これをクライアント側でもう一度Reactに食わすことはできません。
自力で `React.renderToString()` などする必要があります。

以下のページが参考になります。
http://qiita.com/koba04/items/a62a30c6934466ea8dea
https://github.com/mhart/react-server-example

試しに、learnyoureactの最終問題を解いた状態から、サーバ側/クライアント側両方でレンダリングできるようにしてみました
https://github.com/fand/learnyoureact-isomorphic-sample
ほぼ↑の参考ページのコードのコピペですが、一応手元で動作確認をしてます。

サーバ側/クライアント側両方をカバーするとなると結構複雑になるので、骨組みとなるレポジトリなどあるといいかもしれません。

**Comment by kohei-takata** [comment]
コメントありがとうございます！
参考ページ、そして作成していただいたサンプルを確認いたしました。
これで上手くいくような気がします！
本当にありがとうございます :+1: :+1: :+1: 

こちらでも動作確認、少し修正をして `learnyoureact` にエクササイズを追加したいと思います。
確かに少し複雑になりますね。。。
僕の方でも確認しますが、 `ejs` を使わずに、 `dangerouslySetInnerHTML` でHTMLに直接埋め込んだりとかってできたりしますかね...？
そうすれば少し簡単になるのかなと思います。
現状、  `checkbox` のクリックイベントが上手く動いていないので、それをフロント側でまずは動くようにする、というようなエクササイズを追加して、それから上記のようなエクササイズを追加...というように少しずつ学習者の方にソースを修正させていくことで複雑さを回避していけたらなと思います。

なんにせよ、本当にありがとうございました！

**Comment by kohei-takata** [comment]
手元で動作確認をしました。ちゃんと動きました！
ありがとうございます :+1: 

`ejs` を使わなくてもいけそうです。

**Comment by fand** [comment]
よかったです！ :pray:
