### ISSUE TITLE
exercise 1 error

### ISSUE THREAD

**Issue by js08** [workshopper/learnyoureact#60]
hi, 

I have used the eaxact solution for first exercise, but after i do node program.js and hit the url http://localhost:3000/, I get the follwing error can you tell me why its happening

![screen shot 2015-10-18 at 5 10 49 pm](https://cloud.githubusercontent.com/assets/1699943/10566987/c304ff98-75bb-11e5-82ca-65423bf158a3.png)
 attaching my code structure error too, let me know if I have done anything wrong

![desctop screenshot](https://cloud.githubusercontent.com/assets/1699943/10567019/a3e11f42-75bc-11e5-997e-b6ed7cfcd945.png)

**Comment by kohei-takata** [comment]
The error said that there is no `index.jsx` in `views` directory.
It seems that there is no `views` directory in your workspace.

**Comment by js08** [comment]
@tako-black if you see my above screenshot, I have included the folder structure as well as code in jsx file, so I think there is some other error

**Comment by js08** [comment]
@tako-black any idea about it.

**Comment by kohei-takata** [comment]
Did you try making `views` drectory?

**Comment by js08** [comment]
@tako-black yeah its working.

I have another problem, do you know the solution, providing it below.

I have a react app, in which folder name is sports, inside the sports folder I have node modules, inside the node modules folder I have football folder and react folder.
If go to football folder and do npm install react its installing react, which makes my application fail, how to prevent this command npm install react from being successful.
Is it anyway we can right a script to prevent this process to happen, but it should work when we do npm install react in sports folder. Is there any already npm packages which we use it make automatically validated our npm commands.

**Comment by kohei-takata** [comment]
I have some questions.
1. Is `football` a module of node?
2. If isn't, why do you make `football` folder in `node_modules` folder?
3. Why did you run `npm install react` command, nevertheless `node_modules` folder has `react` folder?
4. What error said when your application fails?
