### ISSUE TITLE
Error in challenge statement (PropTypes)

### ISSUE THREAD

**Issue by peterlazar1993** [workshopper/learnyoureact#73]
Modify TodoList in index.jsx like below.

Before you start, you may want to check your current index.jsx into source control, or create a new index.jsx for this exercise.

import React from 'react';

export default class TodoBox extends React.Component {
  // Omitted
}

class TodoList extends React.Component {
  // Omitted
}

The exercises asks us to modify TodoList as shown.
But no modifications are being made to TodoList.

**Comment by kohei-takata** [comment]
@peterlazar1993 
Thanks for your issue!
I fixed!
