### ISSUE TITLE
Error upon `learnyoureact`

### ISSUE THREAD

**Issue by obligated** [workshopper/learnyoureact#8]
Hi,

recently installed a copy of learnyoureact. Upon launching it via CLI, I got an unexpected error

```
learnyoureact/node_modules/workshopper-adventure/adventure.js:262
      return error(this.__('error.exercise.missing_file', {exerciseFile: meta.
                        ^
TypeError: undefined is not a function
```

Nothing seems to work. If I'm given a few pointers, I wouldn't mind helping out.

All the best,
obligated_user

**Comment by kohei-takata** [comment]
Hi,
Thank you for your reporting a bug.

I know `workshopper-adventure` has some bugs, but I cannot fix that.
`workshopper-adventure` is beta version and no repository now.

I think this bug sometimes happen and at other time not.
Please try `learnyoureact` command several times, and I think no error happen.

**Comment by obligated** [comment]
Hi again.
I was just wondering what workshopper-adventure was.
I had a bit of a snoop around, and came across https://github.com/substack/adventure and https://www.npmjs.com/package/workshopper. You mentioned a `workshopper-adventure` package...as a complete noobie to all this, I was wondering what the differences are?

Cheers

**Comment by and2048** [comment]
Hi,
You need make to lowercase the directory names in ./learnyoureact/exercises

**Comment by kohei-takata** [comment]
@obligated `workshopper-adventure` is the next version of https://github.com/workshopper/workshopper.
https://github.com/substack/adventure cannot use multi languages(i18n).
I used `workshopper-adventure`, because of using multi languages(i18n).
When `workshopper` merge the patch of `workshopper-adventure`, I will change the code to use `workshopper`.

**Comment by kohei-takata** [comment]
@and2048 Hi,
What do you mean by that?
If I change the names of directory for lowercase, the above error doesn't happen?

**Comment by and2048** [comment]
on linux - yes
on windows - I think, this error didn't happen

**Comment by kohei-takata** [comment]
@and2048 OK.
I'll change the names.
Thanks!

**Comment by kohei-takata** [comment]
@obligated 
I've changed the name of directory and `npm publish`ed.
Please use the latest version.

**Comment by obligated** [comment]
Yep, it's working! Thanks a lot!
