### ISSUE TITLE
Exercise 5 Hint no longer compatible with ES2015

### ISSUE THREAD

**Issue by tongrhj** [workshopper/learnyoureact#89]
Exercise 5 on State asks students to

```
Write code to set the initial value of checked and define handleChange.
You can set the initial value of checked in a special getInitialState function.
```

However, with the ES2015 classes used in the code provided, getInitialState no longer works. Rather, students should be assigning bound instances in the constructor as suggested in this Quora answer: http://stackoverflow.com/questions/30720620/reactjs-w-ecmascript-6

I can change the problem description. Please let me know if a pull request is appreciated.

**Comment by kohei-takata** [comment]
Hi @tongrhj !
Thanks for your reporting the issue!
Of course PRs are appreciated!
Could you change?
